version: "3.9"
services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "5000:5000"
    networks:
      - internal_network
    volumes:
      - ./logs:/logs
    privileged: true

  server1:
    build:
      context: ./server
      args:
        SERVER_ID: Server_1
    environment:
      - SERVER_ID=Server_1
    networks:
      - internal_network
    ports:
      - "5001:5000"
    volumes:
      - ./logs:/logs

  server2:
    build:
      context: ./server
      args:
        SERVER_ID: Server_2
    environment:
      - SERVER_ID=Server_2
    networks:
      - internal_network
    ports:
      - "5002:5000"
    volumes:
      - ./logs:/logs

  server3:
    build:
      context: ./server
      args:
        SERVER_ID: Server_3
    environment:
      - SERVER_ID=Server_3
    networks:
      - internal_network
    ports:
      - "5003:5000"
    volumes:
      - ./logs:/logs

  server4:
    build:
      context: ./server
      args:
        SERVER_ID: Server_4
    environment:
      - SERVER_ID=Server_4
    networks:
      - internal_network
    ports:
      - "5004:5000"
    volumes:
      - ./logs:/logs

  server5:
    build:
      context: ./server
      args:
        SERVER_ID: Server_5
    environment:
      - SERVER_ID=Server_5
    networks:
      - internal_network
    ports:
      - "5005:5000"
    volumes:
      - ./logs:/logs

  server6:
    build:
      context: ./server
      args:
        SERVER_ID: Server_6
    environment:
      - SERVER_ID=Server_6
    networks:
      - internal_network
    ports:
      - "5006:5000"
    volumes:
      - ./logs:/logs

networks:
  internal_network:
    driver: bridge
